# Languages
#   Create a `[X]` block for each language you want, where X is the language ID.
#   Refer to https://sourcethemes.com/academic/docs/language/

# Configure the English version of the site.
[en]
  languageCode = "en-us"
  contentDir = "content/en"

[fr]
  languageCode = "fr-fr"
  contentDir = "content/fr"
  title = "Eric Marcon"
  description = "Page personnelle d'Eric Marcon"
  [fr.params]
    description = ""
    date_format = "02-Jan-2006"
    time_format = "15:04"
  [[fr.menu.main]]
    name = "Accueil"
    url = "#about"
    weight = 20
  [[fr.menu.main]]
    name = "Publications"
    url = "#featured"
    weight = 40
  [[fr.menu.main]]
    name = "Communications"
    url = "#talks"
    weight = 60
  [[fr.menu.main]]
    name = "Logiciels"
    url = "#software"
    weight = 70
  [[fr.menu.main]]
    name = "Cours"
    url = "#course"
    weight = 80
  [[fr.menu.main]]
    name = "Articles"
    url = "#posts"
    weight = 90
  [[fr.menu.main]]
    name = "Contact"
    url = "#contact"
    weight = 130
