---
title: "Publications"
header:
  caption: ''
  image: ''
view: 4
---

```{r options, echo=FALSE, message=FALSE}
knitr::opts_chunk$set(cache=FALSE, echo = FALSE, tidy=FALSE, tidy.opts=list(blank=FALSE, width.cutoff=50), out.width='\\maxwidth')
options(width=50)
# Installation des packages si nécessaire et chargement
Library <- function(Packages) {
  InstallAndLoad <- function(Package) {
    if (!Package %in% installed.packages()[, 1]) {install.packages(Package, repos="https://cran.rstudio.com/")}
    require(Package, character.only = TRUE)
  }
  invisible(sapply(Packages, InstallAndLoad))
}
# Ajouter les packages nécessaires ici
Library(c("scholar", "tidyverse", "ggraph", "igraph"))
```


```{r}
library("scholar")
library("tidyverse")
library("ggraph")

AuthorID <- "4iLBmbUAAAAJ" # Eric Marcon
```


```{r coauthors, message=FALSE}
# Paramètres
MinCopublications <- 2
MaxCoauteurs <- 100

library("magrittr")
# Vecteur des coauteurs de publications, sans accents
AuthorID %>% 
  get_publications %>% 
  mutate(AuthorsASCII=iconv(author, from="UTF-8", to="ASCII//TRANSLIT")) %$% 
  AuthorsASCII %>% 
  # Suppression des accents transformés en ' sur MacOS
  str_replace("'", "") ->
  AuthorsASCII
# Auteurs uniques
AuthorsASCII %>% 
  paste(collapse=", ") %>% 
  str_split(pattern=", ") %>% 
  unlist %>% 
  # Uniformisation de la casse
  str_to_upper %>% 
  unique ->
  UniqueAuthors
# Elimination de ... (= et al.)
UniqueAuthors <- UniqueAuthors[UniqueAuthors != "..."]
# Matrice d'autorat: une ligne par article, auteurs en colonnes, valeurs logiques
PaperAuthoredBy <- sapply(UniqueAuthors, function(Author) str_detect(str_to_upper(AuthorsASCII), Author))
# Filtrage des auteurs
tibble(Author=UniqueAuthors, NbPapers=colSums(PaperAuthoredBy)) %>% 
  filter(NbPapers >= MinCopublications) %>% 
  arrange(desc(NbPapers)) %>% 
  slice(1:MaxCoauteurs) ->
  NbPapersPerAuthor
# Recalcul de la matrice d'autorat réduite
PaperAuthoredBy <- sapply(NbPapersPerAuthor$Author, 
                          function(Author) str_detect(str_to_upper(AuthorsASCII), Author))
# Matrice d'adjacence
adjacencyMatrix <- t(PaperAuthoredBy) %*% PaperAuthoredBy
# Graphe d'adjacence  
library("igraph")
g <- graph.adjacency(adjacencyMatrix, mode = "undirected", diag = FALSE)
V(g)$Degree <- degree(g, mode = 'in') # Nombre de liens
V(g)$Name <- NbPapersPerAuthor$Author # Etiquettes des noeuds
# Figure
library("ggraph")
ggraph(g, layout = "auto") + 
  geom_edge_link(aes(alpha = 1/2, color = .data[["from"]]), 
                         alpha = 1/3, show.legend = FALSE) + 
  geom_node_point(aes(size = .data[["Degree"]]), 
                          alpha = 1/2, show.legend = FALSE) +
  geom_node_text(aes(label = .data[[str_to_title("Name")]]), 
                         size = 5, repel = TRUE, check_overlap = TRUE) + 
  labs(title = paste("Réseau de co-autorat de", get_profile(AuthorID)$name),
       subtitle = "Publications citées au moins une fois dans Google Scholar",
       caption = paste("Coauteurs avec au moins", MinCopublications, "co-publications")) +
  theme_graph(title_size = 16, base_family = "sans")
```

Indice h: `r AuthorID %>% get_profile %>% pluck("h_index")`.

```{r citations, message=FALSE}
AuthorID %>% 
  get_citation_history %>% 
  ggplot(aes(year, cites)) +
    geom_segment(aes(xend = year, yend = 0), linewidth=1, color='darkgrey') +
    geom_point(size=3, color='firebrick') +
    labs(title = "Citations par année", 
         caption = "Source: Google Scholar",
         x = "Année",
         y = "Citations")
```
