# Prepare index.md files for publications
#++++++++++++++++++++++++++++++++++++++++
#
# Adapted from:
# https://raw.githubusercontent.com/juancarloscastillo/starter-hugo-academic/master/content/publication/bibtex_2academic.R
#
# bibfile is exported from Zotero as BiLaTeX

# The function: bibtex_2academic ----
bibtex_2academic <- function(
    bibfile,
    outfold,
    abstract = TRUE,
    overwrite = FALSE) {

  # Packages
  if (!require("pacman")) install.packages("pacman")
  pacman::p_load(RefManageR, dplyr, stringr, anytime, tidyr, stringi, magrittr)

  # Import the bibtex file and convert to data.frame
  mypubs <- ReadBib(
    bibfile,
    check = "warn",
    .Encoding = "UTF-8"
  ) %>%
    as.data.frame()

  # Add rownames ad ID's
  mypubs$ID <- rownames(mypubs)

  mypubs %<>%
    mutate(mainref = journaltitle)
  mypubs$mainref %<>%
    #otherwise it appears "NA" in post
    replace_na('')

  mypubs$abstract %<>%
    #otherwise it appears "NA" in post
    replace_na('(Abstract not available)')

  # Customize Zotero extra field (here "annotation") in order to leave there
  # the additional information for the md file
  #  mypubs$annotation %<>% replace_na('image_preview = ""')

  #clean backslashes generated by conversion of underline characters in links (_)
  # mypubs$annotation<- gsub(
  #   pattern = ('\\\\'),
  #   replacement = '',
  #   x = mypubs$annotation
  # )

  mypubs$abstract <- gsub(
    pattern = ('\\\\'),
    replacement = '',
    x = mypubs$abstract
  )

  mypubs$mainref <- gsub(
    pattern = ('\\\\'),
    replacement = '',
    x = mypubs$mainref
  )

  # Customize for more than one editor

  mypubs$editor <- gsub(
    pattern = (' and '),
    replacement = ', ',
    x = mypubs$editor
  )

  mypubs$editor <- stri_replace_last_fixed(mypubs$editor, ',', ' &')

  # add characters between tags for properly render
  mypubs$keywords <- gsub(
    pattern = (','),
    replacement = '","',
    x = mypubs$keywords
  )

  #add line breaks for the different entries
  # mypubs$annotation<-cat(stri_wrap(mypubs$annotation, whitespace_only = TRUE))

  # assign "categories" to the different types of publications
  mypubs %<>%
    dplyr::mutate(
      pubtype = dplyr::case_when(
        bibtype == "Article" ~ "2",
        bibtype == "Article in Press" ~ "2",
        bibtype == "InProceedings" ~ "1",
        bibtype == "Proceedings" ~ "1",
        bibtype == "Conference" ~ "1",
        bibtype == "Conference Paper" ~ "1",
        bibtype == "MastersThesis" ~ "3",
        bibtype == "PhdThesis" ~ "3",
        bibtype == "Manual" ~ "4",
        bibtype == "TechReport" ~ "4",
        bibtype == "Book" ~ "5",
        bibtype == "InCollection" ~ "6",
        bibtype == "InBook" ~ "6",
        bibtype == "Misc" ~ "0",
        TRUE ~ "0"
      )
    )

  # apply the "create_md" function over the publications list to generate
  # the different "md" files.
  apply(
    mypubs,
    MARGIN = 1,
    FUN = create_md,
    # Arguments
    outfold = outfold,
    abstract = abstract,
    overwrite = overwrite
  )
}


# Utility: write each md file ----
create_md <- function(x, outfold, abstract, overwrite) {

  # Make a date according to pattern YYYY-MM-DD
  if (is.na(x["date"])) {
    x["date"] <- "2999-01-01"
  } else if (nchar(x["date"]) == 4) {
    x["date"] <- paste0(x["date"], "-01-01")
  } else if (nchar(x["date"]) == 7) {
    x["date"] <- paste0(x["date"], "-01")
  }

  filename <- paste0(x["ID"], ".md")
  # start writing
  if (!file.exists(file.path(outfold, filename)) | overwrite) {
    fileConn <- file.path(outfold, filename)
    write("+++", fileConn)

    # Title and date
    write(paste0("title = \"", x["title"], "\""), fileConn, append = T)
    write(paste0("date = \"", anydate(x[["date"]]), "\""), fileConn, append = T)

    # Authors. Comma separated list, e.g. `["Bob Smith", "David Jones"]`.
    auth_hugo <- str_replace_all(x["author"], " and ", "\", \"")
    auth_hugo <- stringi::stri_trans_general(auth_hugo, "latin-ascii")
    write(paste0("authors = [\"", auth_hugo,"\"]"), fileConn, append = T)

    # Publication type. Legend:
    # 0 = Uncategorized, 1 = Conference paper, 2 = Journal article
    # 3 = Manuscript, 4 = Report, 5 = Book,  6 = Book section
    write(
      paste0("publication_types = [\"", x["pubtype"],"\"]"),
      fileConn,
      append = T
    )

    # Publication details

    publication <- x["mainref"]
    if ("editor" %in% names(x) && !is.na(x["editor"])) {
      publication <- paste0(publication, " In ", x["editor"], ": ")
    }
    if ("booktitle" %in% names(x) && !is.na(x["booktitle"])) {
      publication <- paste0(publication, x["booktitle"], ". ")
    }
    if ("volume" %in% names(x) && !is.na(x["volume"])) {
      publication <- paste0(publication, ", ", x["volume"], "")
    }
    if ("type" %in% names(x) && !is.na(x["type"])) {
       publication <- paste0(publication, x["type"], " ")
    }
    if ("number" %in% names(x) && !is.na(x["number"])) {
      publication <- paste0(publication, "(", x["number"], ")")
    }
    if ("pages" %in% names(x) && !is.na(x["pages"])) {
      publication <- paste0(publication, " ", x["pages"], ".")
    }
    if ("address" %in% names(x) && !is.na(x["address"])) {
      publication <- paste0(publication," ", x["address"], ":")
    }
    if ("institution" %in% names(x) && !is.na(x["institution"])) {
      publication <- paste0(publication, " ", x["institution"])
    }
    if ("publisher" %in% names(x) && !is.na(x["publisher"])) {
      publication <- paste0(publication, " ", x["publisher"])
    }
    if ("doi" %in% names(x) && !is.na(x["doi"])) {
      publication <- paste0(publication, " ", paste0("https://doi.org/", x["doi"]))
    }
    if ("isbn" %in% names(x) && !is.na(x["isbn"])) {
      publication <- paste0(publication, ". ISBN: ", paste0(x["isbn"]))
    }

    write(paste0("publication = \"", publication, "\""), fileConn, append = T)
    write(paste0("publication_short = \"", publication,"\""), fileConn, append = T)

    # Abstract and optional shortened version.
    write(paste0("abstract = \"", x["abstract"], "\""), fileConn, append = T)
    #      if (abstract) {
    #        write(paste0("abstract = \"", x["abstract"],"\""), fileConn, append = T)
    #      } else {
    #        write("abstract = \"\"", fileConn, append = T)
    #      }
    write(paste0("abstract_short = \"", "\""), fileConn, append = T)

    # Source document from Zotero URL field

    if ("url" %in% names(x) && !is.na(x["url"])) {
      write(paste0("url_source = \"", x["url"], "\""), fileConn, append = T)
    }
    if ("keywords" %in% names(x) && !is.na(x["keywords"])) {
      write(paste0("tags = [\"", x["keywords"], "\"]"), fileConn, append = T)
    }

    # other possible fields are kept empty. They can be customized later by
    # editing the created md

    write("url_code = \"\"", fileConn, append = T)
    write("image_preview = \"\"", fileConn, append = T)
    write("selected = false", fileConn, append = T)
    write("projects = []", fileConn, append = T)

    #links
    write("url_pdf = \"\"", fileConn, append = T)
    write("url_preprint = \"\"", fileConn, append = T)
    write("url_dataset = \"\"", fileConn, append = T)
    write("url_project = \"\"", fileConn, append = T)
    write("url_slides = \"\"", fileConn, append = T)
    write("url_video = \"\"", fileConn, append = T)
    write("url_poster = \"\"", fileConn, append = T)

    #other stuff
    write("math = true", fileConn, append = T)
    write("highlight = true", fileConn, append = T)
    # Featured image
    write("[header]", fileConn, append = T)
    write("image = \"\"", fileConn, append = T)
    write("caption = \"\"", fileConn, append = T)

    write("+++", fileConn, append = T)

    # Any other relevant information from Zotero: write in the "Extra" field
    if ("annotation" %in% names(x) && !is.na(x["annotation"])) {
      write(paste0(x["annotation"]), fileConn, append = T)
    }

    # Dimension
    if ("doi" %in% names(x) && !is.na(x["doi"])) {
      write(
        paste0(
          "<span class=\"__dimensions_badge_embed__\" data-doi=\"",
          x["doi"],
          "\"></span><script async src=\"https://badge.dimensions.ai/badge.js\" charset=\"utf-8\"></script>"
        ),
        fileConn,
        append = T
      )
    }
  }
}

# Running the function ----

my_bibfile <- "assets/publications.bib"
bibtex_2academic(
  bibfile   = my_bibfile,
  # This folder must exist
  outfold   = "assets/publication",
  abstract  = TRUE,
  overwrite = TRUE
)
# Copy the content of each file into content/<lang>/publication/<publication ID>/index.md
# along with the bibtex citation in cite.bib
