---
title: Publications

# View.
#   1 = List
#   2 = Compact
#   3 = Card
#   4 = Citation
view: 4
---

```{r options, include=FALSE}
set.seed(973)
knitr::opts_chunk$set(
  cache = FALSE, 
  echo = FALSE, 
  tidy = FALSE, 
  tidy.opts = list(blank = FALSE, width.cutoff = 50), 
  out.width = '\\maxwidth'
)
options(width = 50)
# Installation des packages si nécessaire
install_packages <- function(packages) {
  install_package <- function(package) {
    if (!package %in% installed.packages()[, 1]) {
      install.packages(package, repos = "https://cran.rstudio.com/")
    }
  }
  invisible(sapply(packages, install_package))
}
# Ajouter les packages nécessaires ici
install_packages(c("bib2df", "scholar", "tidyverse", "ggraph", "igraph"))
```


```{r}
AuthorID <- "4iLBmbUAAAAJ" # Eric Marcon
```


```{r coauthors, message=FALSE, warning=FALSE}
# Paramètres
# Auteur principal
author_focus <- "Marcon, E"
# Nombre minimal de copuplications pour figurer sur le graphique
copublication_min <- 2

library("bib2df")
# Création d'un dataframe des publications
"../../../assets/publications.bib" %>%
  bib2df() %>%
  filter(!is.na(TITLE)) ->
  bib_df

# Auteurs uniques
bib_df %>%
  pluck("AUTHOR") %>%
  unlist() %>%
  # Elimination des accolades
  str_replace(pattern = "\\{", replacement = "") %>%
  str_replace(pattern = "\\}", replacement = "") %>%
  # Extraction de Nom, Initiale du prénom
  str_extract(pattern = ".+, .") %>%
  unique() %>%
  sort() ->
  authors_unique

# Matrice d'autorat: une ligne par article, auteurs en colonnes, valeurs logiques
# author_detect retourne TRUE si author_name se trouve dans le vecteur authors
# Dans les publications collectives (plus de collective_paper_threshold auteurs),
# les authors_first premiers et authors_last derniers auteurs et author_focus
# sont les seuls pris en compte
author_detect <- function(
    authors,
    author_name,
    author_focus,
    collective_paper_threshold = 20,
    authors_first = 3,
    authors_last = 1
    ) {
  authors_nb <- length(authors)
  if (authors_nb > collective_paper_threshold) {
    authors_main <- authors[c(
      1:authors_first,
      (authors_nb + 1 - authors_last):authors_nb
    )]
    if (sum(str_detect(authors, author_name)) > 0)  {
      authors <- c(authors_main, author_focus)
    } else {
      authors <- authors_main
    }
  }
  authors %>% 
    # Vecteur de détection
    str_detect(author_name) %>% 
    # Retour de TRUE si au moins une valeur est vraie
    sum %>% 
    as.logical()
}

# is_author retourne un vecteur logique indiquant si author_name est auteur de 
# chaque publication de bib_df, avec une attention particulière à author_focus
# cf. author_detect()
is_author <- function(author_name, bib_df, author_focus) {
  bib_df %>%
    pluck("AUTHOR") %>%
    sapply(
      FUN = author_detect, 
      author_name = author_name, 
      author_focus = author_focus
    )
}

# Matrice d'autorat: publications en lignes, auteurs en colonnes, valeurs logiques
paper_is_authored_by <- sapply(
  authors_unique,
  FUN = is_author,
  bib_df = bib_df,
  author_focus = author_focus
)

# Filtrage des auteurs avec plus de copublication_min publications
tibble(
  author = authors_unique, 
  papers_nb = colSums(paper_is_authored_by, na.rm = TRUE)
) %>%
  filter(papers_nb >= copublication_min) %>%
  arrange(desc(papers_nb)) ->
  papers_nb_per_author

# Recalcul de la matrice d'autorat réduite
paper_is_authored_by <- sapply(
  papers_nb_per_author$author, 
  FUN = is_author,
  bib_df = bib_df,
  author_focus = author_focus
)

# Matrice d'adjacence
adjacencyMatrix <- t(paper_is_authored_by) %*% paper_is_authored_by

# Graphe d'adjacence
library("igraph")
g <- graph.adjacency(
  adjacencyMatrix, 
  mode = "undirected", 
  diag = FALSE
)
# Nombre de liens
V(g)$Degree <- degree(g, mode = 'in') 
# Etiquettes des noeuds
V(g)$Name <- papers_nb_per_author$author 
# Figure
library("ggraph")
ggraph(g, layout = "auto") +
  geom_edge_link(
    aes(alpha = 1/2, color = .data[["from"]]),
    alpha = 1/3, 
    show.legend = FALSE
  ) +
  geom_node_point(
    aes(size = .data[["Degree"]]),
    alpha = 1/2, 
    show.legend = FALSE
  ) +
  geom_node_text(
    aes(label = .data[[str_to_title("Name")]]),
    size = 5, 
    repel = TRUE, 
    check_overlap = TRUE
  ) +
  labs(
    title = "Coauthorship Network",
    caption = paste(
      "Coauthors with at least", 
      copublication_min, 
      "co-publications")
  ) +
  theme_graph(title_size = 16, base_family = "sans")
```


h Index: `r AuthorID %>% get_profile() %>% pluck("h_index")` ([Google Scholar](`r paste0("https://scholar.google.com/citations?user=", AuthorID)`)).

```{r citations, message=FALSE}
AuthorID %>%
  get_citation_history()  %>% 
  ggplot(aes(year, cites)) +
    geom_segment(
      aes(xend = year, yend = 0), 
      linewidth = 1, 
      color = 'darkgrey'
    ) +
    geom_point(size = 3, color = 'firebrick') +
    labs(
      title = "Citations per year", 
      caption = "Source: Google Scholar"
    )
```
